services:

    chat.publish-stored-events-to-rabbit-mq-command:
        class: Gaming\Chat\Presentation\Console\PublishStoredEventsToRabbitMqCommand
        public: false
        arguments:
            - '@chat.event-store'
            - '@chat.predis'
            - '@chat.message-broker'
        tags:
            -  { name: console.command }

    chat.rabbit-mq-command-listener-command:
        class: Gaming\Chat\Presentation\Console\RabbitMqCommandListenerCommand
        public: false
        arguments:
            - '@chat.message-broker'
            - '@chat.command-bus'
        tags:
            -  { name: console.command }
