version: '3.4'

services:
    ##############################
    #  Database and application  #
    ##############################
    traefik:
        image: marein/php-gaming-website:traefik
        ports:
            - "80:80"
        links:
            - nchan
            - service-js-polyfill
            - nginx
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    mysql:
        image: marein/php-gaming-website:mysql
        command: mysqld
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - mysql:/var/lib/mysql
        restart: on-failure
    redis:
        image: marein/php-gaming-website:redis
        command: redis-server --appendonly yes
        volumes:
            - redis:/data
        restart: on-failure
    rabbit-mq:
        image: marein/php-gaming-website:rabbit-mq
        hostname: rabbit-mq
        volumes:
            - rabbit-mq:/var/lib/rabbitmq/mnesia
        restart: on-failure
    nchan:
        image: marein/php-gaming-website:nchan
        restart: on-failure
        labels:
            - "traefik.enable=true"
            - "traefik.priority=20"
            - "traefik.frontend.rule=PathPrefix:/sse"
    service-js-polyfill:
        image: gamingplatform/service-js-polyfill
        restart: on-failure
        labels:
            - "traefik.enable=true"
            - "traefik.priority=20"
            - "traefik.frontend.rule=PathPrefixStrip:/polyfill"
    nginx:
        image: marein/php-gaming-website:nginx
        links:
            - php-fpm
        restart: on-failure
        labels:
            - "traefik.enable=true"
            - "traefik.priority=10"
            - "traefik.frontend.rule=PathPrefix:/"
    php-fpm:
        image: marein/php-gaming-website:php-fpm
        environment:
            APPLICATION_ENVIRONMENT: prod
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        restart: on-failure

    ##############################
    #   Long running processes   #
    ##############################
    php-connect-four-build-query-model:
        image: marein/php-gaming-website:php-fpm
        command: bin/console connect-four:build-query-model --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        restart: on-failure
    php-connect-four-publish-stored-events-to-rabbit-mq:
        image: marein/php-gaming-website:php-fpm
        command: bin/console connect-four:publish-stored-events-to-rabbit-mq --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        restart: on-failure
    php-chat-publish-stored-events-to-rabbit-mq:
        image: marein/php-gaming-website:php-fpm
        command: bin/console chat:publish-stored-events-to-rabbit-mq --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        restart: on-failure
    php-identity-publish-stored-events-to-rabbit-mq:
        image: marein/php-gaming-website:php-fpm
        command: bin/console identity:publish-stored-events-to-rabbit-mq --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        restart: on-failure
    php-web-interface-publish-running-games-count-to-nchan:
        image: marein/php-gaming-website:php-fpm
        command: bin/console web-interface:publish-running-games-count-to-nchan --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        restart: on-failure
    php-web-interface-publish-rabbit-mq-events-to-nchan:
        image: marein/php-gaming-website:php-fpm
        command: bin/console web-interface:publish-rabbit-mq-events-to-nchan --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        restart: on-failure
    php-chat-command-listener:
        image: marein/php-gaming-website:php-fpm
        command: bin/console chat:command-listener --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        restart: on-failure
    php-connect-four-referee:
        image: marein/php-gaming-website:php-fpm
        command: bin/console connect-four:referee --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        restart: on-failure

volumes:
    mysql:
    redis:
    rabbit-mq:
