imports:
    - { resource: chat/config.yml }
    - { resource: connect-four/config.yml }
    - { resource: identity/config.yml }
    - { resource: web-interface/config.yml }

framework:
    secret: '%env(APPLICATION_KERNEL_SECRET)%'
    templating:
        engines: ['twig']
    validation:
        enabled: true
    router:
        resource: "%kernel.project_dir%/config/routing.yml"

doctrine:
    dbal:
        types:
            uuid_binary_ordered_time: Ramsey\Uuid\Doctrine\UuidBinaryOrderedTimeType
            uuid_binary: Ramsey\Uuid\Doctrine\UuidBinaryType
        mapping_types:
            uuid_binary_ordered_time: binary
            uuid_binary: binary

monolog:
    handlers:
        application_error:
            type: stream
            path: "php://stderr"
            level: error

services:
    # Custom exception listener for the gaming domain.
    # Lower priority so that the profiler is respected.
    gaming.exception-to-json-listener:
        class: Gaming\Common\Port\Adapter\Symfony\GamingExceptionListener
        public: false
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: -100 }
