services:

    # This is pretty ugly. We can use tags, or create this via a factory in php.
    connect-four.query-bus:
        class: Gaming\Common\Bus\CallableBus
        public: false
        calls:
            - [
                addHandler,
                [
                  'Gaming\ConnectFour\Application\Game\Query\GameQuery',
                  '@connect-four.query.game-handler'
                ]
              ]
            - [
                addHandler,
                [
                  'Gaming\ConnectFour\Application\Game\Query\GamesByPlayerQuery',
                  '@connect-four.query.games-by-player-handler'
                ]
              ]
            - [
                addHandler,
                [
                  'Gaming\ConnectFour\Application\Game\Query\OpenGamesQuery',
                  '@connect-four.query.open-games-handler'
                ]
              ]
            - [
                addHandler,
                [
                  'Gaming\ConnectFour\Application\Game\Query\RunningGamesQuery',
                  '@connect-four.query.running-games-handler'
                ]
              ]

    connect-four.query.game-handler:
        class: Gaming\ConnectFour\Application\Game\Query\GameHandler
        public: false
        arguments:
            - '@connect-four.game-finder'

    connect-four.query.games-by-player-handler:
        class: Gaming\ConnectFour\Application\Game\Query\GamesByPlayerHandler
        public: false
        arguments:
            - '@connect-four.games-by-player-store'

    connect-four.query.open-games-handler:
        class: Gaming\ConnectFour\Application\Game\Query\OpenGamesHandler
        public: false
        arguments:
            - '@connect-four.open-game-store'

    connect-four.query.running-games-handler:
        class: Gaming\ConnectFour\Application\Game\Query\RunningGamesHandler
        public: false
        arguments:
            - '@connect-four.running-games-store'
